version: '3'
services:
  {{Name}}:
    build: .
    image: 978577353296.dkr.ecr.eu-west-1.amazonaws.com/{{Name}}:${VERSION:-latest}
    environment:
      - LOG_LEVEL=warning
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB={{Name}}
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - OAUTH_CLIENT_ID=
      - OAUTH_CLIENT_SECRET=
      - OAUTH_JWT_SECRET=test
      - DD_AGENT_ADDR=
      - DD_SERVICE_NAME={{Name}}
      - DD_TRACING_ENABLED=false
      - ALLOWED_ORIGINS="http://localhost:8081"
      - SERVER_PORT=8081
      - SERVER_HOST=127.0.0.1
      - POSTGRES_MAX_OPEN_CONNS=100
      - HTTP_TIMEOUT=3
      - ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - ALLOWED_HEADERS=Origin,X-Requested-With,Content-Type,Accept,X-Auth,Purchase-Token
      - CREDENTIALS=true
    ports:
      - "8888:8888"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB={{Name}}
    ports:
      - "5433:5432"
    volumes:
      - pg-volume:/var/lib/postgresql/data/pgdata
volumes:
  pg-volume:
