apiVersion: batch/v1
kind: Job
metadata:
  name: dev-dbmigrate
  labels:
    jobgroup: dev-dbmigrate
spec:
  template:
    metadata:
      name: dev-dbmigrate
      labels:
        jobgroup: dev-dbmigrate
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: eu-west-1-ecr-registry
      containers:
      - name: app
        image: 978577353296.dkr.ecr.eu-west-1.amazonaws.com/{{Name}}:APPIMAGEPLACEHOLDER
        command: ["sh", "-c", "cd /go/bin ; ./migration up"]
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: DB_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: db_password
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: DB_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: db_username
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: POSTGRES_MAX_OPEN_CONN
          value: "10"